### ISSUE TITLE
Question: May I read you project source code ?

### ISSUE THREAD

**Issue by yileye** [VikParuchuri/apartment-finder#14]
Beause I can not see source code in CitHub.

I want to know more about this project

**Comment by marcthayer** [comment]
@yileye All the code is accessible from https://github.com/VikParuchuri/apartment-finder. From there I downloaded a zip file of the current code: 
[apartment-finder-master.zip](https://github.com/VikParuchuri/apartment-finder/files/686958/apartment-finder-master.zip)

**Comment by yileye** [comment]
Thanks , I will try.
