### ISSUE TITLE
no module named craigslist

### ISSUE THREAD

**Issue by danielguerra** [VikParuchuri/apartment-finder#20]
daniel@865c00180794:/opt/wwc/apartment-finder# python scraper.py 
Traceback (most recent call last):
  File "scraper.py", line 1, in <module>
    from craigslist import CraigslistHousing
ImportError: No module named craigslist

**Comment by szl0072** [comment]
you have to install craigslist first.

**Comment by danielguerra** [comment]
I tried two methods

1.  Update requirements file and let docker get the lastest and then 2.
 launching docker and connecting to the instance. But pip update wasn't
working that way.

what way should I be doing? This is my first time using docker

**Comment by danielguerra** [comment]
from within the docker instance I ran:

pip3 install python-craigslist --upgrade

everything is working now
